enum ErrorsEnum {
  TREE_CREATE_ERROR = 'TREE_CREATE_ERROR',
  TREE_DELETE_ERROR = 'TREE_DELETE_ERROR',
  TREE_MOVE_ERROR = 'TREE_MOVE_ERROR',
  TREE_LIST_ERROR = 'TREE_LIST_ERROR',
  TREE_PARENT_DIR = 'Parent dir not found',
}

export default ErrorsEnum;
